### PR TITLE
Add python 2.7 support

### PR DESCRIPTION
**Pull request by adamlwgriffiths**
Adds python 2.7 support.
I'm unable to fully run the tests. I can however run the example code.
Might break python 3, I don't have much experience with it.

### CODE REVIEW

**Comment by xethorn** [comment]
Thanks @adamlwgriffiths for adding python 2.7 support. This looks great. Travis is showing errors for python 2.7 on `test_activities.py`. Can you take a look?

Also, I usually like to have one commit per pull request. When everything is good (all the tests have passed), would you mind squashing your commits into one?

**Comment by adamlwgriffiths** [comment]
I'm not sure what the issue is. I was hoping you might have some clue about where to look.

Re: squashing; sure, I didn't expect this to get merged immediately =)

**Comment by xethorn** [comment]
The error isn't very straightforward. 

Are you able to run py.test locally and get the same issue? If so, can you inspect the mock and see if the values are correct? If you haven't used py.test in the past, you can specify `--pdb` at execution, it will allow you to debug when it fails. 

Re: squashing. Your code looks great. A good contribution has no reason to be held back.

**Comment by adamlwgriffiths** [comment]
```
        for current_activity in worker.activities:
>           assert current_activity.run.called
E           assert <MagicMock id='4337657360'>.called
E            +  where <MagicMock id='4337657360'> = <Activity 'activity_4-1.0' at 0x1028bb910>.run

tests/test_activity.py:171: AssertionError
<snip>
(Pdb) p current_activity.run.called
True
```

So I changed the check from
```
assert current_activity.run.called
```
to
```
assert True == current_activity.run.called
```

And it fixes the assertion.
Something strange is going on with mock. It doesn't trigger this with any of the other tests, even with exactly the same line of code in them. And these identical code blocks are being called because I can replace them with an `assert False` and it fails.

I can commit that change, but I'm hesitant to because it's obviously covering something up. Even if it's a bug in mock.

**Comment by xethorn** [comment]
What value do you get if you use `call_count`?

**Comment by adamlwgriffiths** [comment]
```
(Pdb) p current_activity.run.call_count
1
```

=/

**Comment by xethorn** [comment]
Are all the 4 activities returning 1? If so, then let's switch to `current_activity.run.call_count == 1`. All activities should have been called only one time (that's what `called` was checking really.)

**Comment by adamlwgriffiths** [comment]
Passes with that check. Happy for it to be committed?
I'll add a comment regarding it. Still covering up some strange mock behavior.

**Comment by xethorn** [comment]
Yes – happy to merge it. It's only an issue with 2.7 – so it wouldn't impact any of the most recent. Before I can merge, can you please squash? :) Thanks!

**Comment by adamlwgriffiths** [comment]
Updated unit test, added comment, hopefully squashed correctly =P.

**Comment by adamlwgriffiths** [comment]
Hmm, it dropped the last commit?

**Comment by adamlwgriffiths** [comment]
Ok, got it that time. Git and me aren't friends.
Still, strange that travis didn't complain.

**Comment by mortaliorchard** [comment]
@adamlwgriffiths : quick question are you still using garcon? What do you think about it?

**Comment by adamlwgriffiths** [comment]
Honestly I didn't get far with it. A change in our project requirements made it seem like AWS SWF was no longer feasible, but that may no longer be the case and I may be able to use SWF again.
Development has been delayed however, so I cannot really give you any detailed feedback. 

While I was doing research into Python and AWS, Garcon seemed to be the only library available (when searching ddg + gh).
The design was simple and it seemed to do everything I wanted without all the standard Boto boilerplate.
Essentially I just want to define functions, and hook them up to events. Then connect those together. Simple.
If I'd written the lib myself, I would've tried to make it the same as you have. Hence, I decided to port it to Py 2.7. =)

I believe for a separate project we're looking at using AWS Kinesis (good for parsing large data streams). But thats only being supported in the new, pre-release, Boto. So that space is also ripe for making 'pythonic' and would probably be quite big for the 'big data' users of python.

**Pull request merged**
