### PR TITLE
Add ExecutionContext

### PR DESCRIPTION
**Pull request by xethorn**
The execution context allows to separate the different elements that
forms the full execution context: from the workflow execution input
to the full context.

@rantonmattei @someboredkiddo

### CODE REVIEW

**Comment by rantonmattei** [comment]
You have a failing build

**Comment by rantonmattei** [comment]
What's the need behind this? To separate input from current context? Can you give more "context" :grin:?

**Comment by someboredkiddo** [comment]
When writing a custom decider, you can now use the current context when making decisions about what to schedule

ex.
def decider(self, schedule, context):
    # disclaimer still need to play with this part to confirm syntax
    if context.get('bootstrap.do_optional_activity'):
       schedule('activity_a', self.optional_activity)

This is particularly useful for grabbing the initial context when a flow is first executed and making different different bootstrap decisions

**Comment by xethorn** [comment]
Any update on this?

**Comment by rantonmattei** [comment]
R+

**Comment by glennyonemitsu** [comment]
R+

**Comment by someboredkiddo** [comment]
:+1:

**Pull request merged**
